### ISSUE TITLE
Cant login even with working db

### ISSUE THREAD

**Issue by b14ckyy** [pernicious-flier/FPVlogbook#1]
Hello, 

I'm sitting here since hours now to solve the issue that I cannot log in. 

Apache 2.2 is installed
PHP 5.6 is installed and active as it reports the correct version
MySQL is up and running

I create a new user
checked PHPMyAdmin and new user is listed in the database
set user account as active (Yes) and saved
try to login > password and name field resets and no log in possible

tried that on a raspberry pi on raspian first with the same result but i was only able to install PHP7 here. So i tried on Ubuntu on my Laptop too but I ended on the same issue with PHP 5.6. SQL database is working. I also tried to edit register.php for auto-active accounts but still the same issue. See screenshot attached. 
![image](https://user-images.githubusercontent.com/33039058/59067114-125a2f80-88b1-11e9-9f33-d01327fb214a.png)

**Comment by b14ckyy** [comment]
Is this tool even developed anymore? :(

**Comment by pernicious-flier** [comment]
Hello b14ckyy,
sorry for the late reply .. i've just tested the code to check that everything's fine and it worked fine.
This is what i did:
- downloaded the code from here (just to be sure)
- downloaded usbwebserver 8.5, wich is good and fast for development (but I've tested on server also and works the same)
- opened phpmyadmin and executed the sql query (copy and paste db.sql), this has created the database
- modified the file dbinit.php with the db's username and password, for usbwebserver are:
define ( 'dbhost', 'localhost');
define ( 'DBUSER', 'root');
define ( 'DBPASS', 'usbw');
define ( 'DBNAME', 'fpvlog');
-opened the homepage on localhost (for usbwebserver is http: // localhost:8080 )
-registered a new user
-opened phpmyadmin and changed the "fpvlog-> members-> active" field with "Yes"
-back to homepage and logged in with success!

I have php 5.3.9, mysql 5.5.20, apache 2.2.21 .
I sincerely think that your setup is fine, just check the "dbinit.php" step that you didn't mentioned in your post.
Best Fla

**Comment by b14ckyy** [comment]
With the USB Web Server it worked now. Thanks for your help!
Will soon try to get it running on a dedicated webserver again and check carefully for all the steps.
