### ISSUE TITLE
Rework of the parsed FC settings needed

### ISSUE THREAD

**Issue by b14ckyy** [pernicious-flier/FPVlogbook#7]
Changes:
Add FF to pitch, roll and yaw PID
Add Servo Update Rate

remove non supported values
discuss maybe other new values

![image](https://user-images.githubusercontent.com/33039058/81733557-7f4b5180-9492-11ea-9716-2235da563d7c.png)

**Comment by pernicious-flier** [comment]
Fixed to work with blackbox tools 0.4.4 also
